import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs"
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme-provider"
import { cn } from "@/lib/utils";
import { AutoLogoutWrapper } from "@/components/Auto-Logout-Wrapper";
import SystemAnalytics, { DevAnalytics } from "@/components/System-Analytics-Sentry";

const firaCode = Fira_Code({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: "Hygieia | IHMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="dark" style={{ colorScheme: "dark" }} suppressHydrationWarning>
        <body
          className={cn(
            "min-h-screen bg-dark-300 font-sans antialiased remove-scrollbar",
            firaCode.variable
          )}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
            disableTransitionOnChange
          >

            <AutoLogoutWrapper>
              <SystemAnalytics>
                {children}
                <DevAnalytics />
              </SystemAnalytics>
            </AutoLogoutWrapper>

            <Toaster richColors position='top-right' expand closeButton visibleToasts={4} />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}

{/*}
import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs"
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme-provider"
import { cn } from "@/lib/utils";
 
const firaCode = Fira_Code({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: "Hygieia | IHMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="dark" style={{ colorScheme: "dark" }} suppressHydrationWarning>
        <body
          className={cn(
            "min-h-screen bg-dark-300 font-sans antialiased remove-scrollbar",
            firaCode.variable
          )}
        >
          <ThemeProvider 
            attribute="class" 
            defaultTheme="dark" 
            enableSystem={false}
            disableTransitionOnChange
          >
            {children}
            <Toaster richColors position='top-center' />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
  */}